-- Cantoa v18.8.50 cumulative hardening migration. Safe to run repeatedly.
-- Run after the base supabase-setup.sql. It includes the v18.8.49 hardening so
-- a deployment upgrading from v18.8.48 can run this file directly.

alter table public.memberships add column if not exists billing_country text;

create table if not exists public.stripe_webhook_events (
  event_id text primary key,
  processed_at timestamptz
);
alter table public.stripe_webhook_events add column if not exists status text not null default 'processed';
alter table public.stripe_webhook_events add column if not exists claim_token text;
alter table public.stripe_webhook_events add column if not exists claimed_at timestamptz;
alter table public.stripe_webhook_events alter column processed_at drop not null;
update public.stripe_webhook_events
   set status='processed', processed_at=coalesce(processed_at,now())
 where status is null or status not in ('processing','processed');
create index if not exists stripe_webhook_events_status_idx
  on public.stripe_webhook_events(status,claimed_at);
alter table public.stripe_webhook_events enable row level security;

create table if not exists public.cantoa_public_rate_limits (
  id bigint generated by default as identity primary key,
  fingerprint text not null,
  action text not null,
  created_at timestamptz not null default now()
);
create index if not exists cantoa_public_rate_limits_lookup_idx
  on public.cantoa_public_rate_limits(fingerprint,action,created_at desc);
alter table public.cantoa_public_rate_limits enable row level security;

create or replace function public.check_cantoa_public_rate_limit(
  p_fingerprint text,
  p_action text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean language plpgsql security definer set search_path=public as $$
declare recent_count integer;
begin
  perform pg_advisory_xact_lock(hashtext(left(p_fingerprint,128) || ':' || left(p_action,80)));
  delete from cantoa_public_rate_limits where created_at < now() - interval '24 hours';
  select count(*) into recent_count from cantoa_public_rate_limits
    where fingerprint=left(p_fingerprint,128) and action=left(p_action,80)
      and created_at >= now() - make_interval(secs => greatest(1,p_window_seconds));
  if recent_count >= greatest(1,p_limit) then return false; end if;
  insert into cantoa_public_rate_limits(fingerprint,action)
  values(left(p_fingerprint,128),left(p_action,80));
  return true;
end $$;
revoke all on function public.check_cantoa_public_rate_limit(text,text,integer,integer) from public,anon,authenticated;
grant execute on function public.check_cantoa_public_rate_limit(text,text,integer,integer) to service_role;

-- Serialize authenticated rate-limit count+insert for one user/action so multiple
-- browser tabs cannot race through the same short-window limit concurrently.
create or replace function public.check_cantoa_rate_limit(
  p_user_id uuid,
  p_action text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean language plpgsql security definer set search_path=public as $$
declare recent_count integer;
begin
  perform pg_advisory_xact_lock(hashtext(p_user_id::text || ':' || left(p_action,40)));
  delete from cantoa_rate_limits
   where user_id=p_user_id and created_at < now() - interval '24 hours';
  select count(*) into recent_count from cantoa_rate_limits
   where user_id=p_user_id and action=left(p_action,40)
     and created_at >= now() - make_interval(secs => greatest(1,p_window_seconds));
  if recent_count >= greatest(1,p_limit) then return false; end if;
  insert into cantoa_rate_limits(user_id,action) values(p_user_id,left(p_action,40));
  return true;
end $$;
revoke all on function public.check_cantoa_rate_limit(uuid,text,integer,integer) from public,anon,authenticated;
grant execute on function public.check_cantoa_rate_limit(uuid,text,integer,integer) to service_role;

insert into public.cantoa_schema_migrations(migration_key)
values('v18.8.49_public_rate_limit_billing_country')
on conflict(migration_key) do nothing;
insert into public.cantoa_schema_migrations(migration_key)
values('v18.8.50_atomic_rate_limit_crash_safe_webhooks')
on conflict(migration_key) do nothing;
