-- Cantoa v18.8.49 hardening migration. Safe to run repeatedly.
alter table public.memberships add column if not exists billing_country text;

create table if not exists public.stripe_webhook_events (
  event_id text primary key,
  processed_at timestamptz not null default now()
);
alter table public.stripe_webhook_events enable row level security;

create table if not exists public.cantoa_public_rate_limits (
  id bigint generated by default as identity primary key,
  fingerprint text not null,
  action text not null,
  created_at timestamptz not null default now()
);
create index if not exists cantoa_public_rate_limits_lookup_idx
  on public.cantoa_public_rate_limits(fingerprint,action,created_at desc);
alter table public.cantoa_public_rate_limits enable row level security;

create or replace function public.check_cantoa_public_rate_limit(
  p_fingerprint text,
  p_action text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean language plpgsql security definer set search_path=public as $$
declare recent_count integer;
begin
  perform pg_advisory_xact_lock(hashtext(left(p_fingerprint,128) || ':' || left(p_action,80)));
  delete from cantoa_public_rate_limits where created_at < now() - interval '24 hours';
  select count(*) into recent_count from cantoa_public_rate_limits
    where fingerprint=left(p_fingerprint,128) and action=left(p_action,80)
      and created_at >= now() - make_interval(secs => greatest(1,p_window_seconds));
  if recent_count >= greatest(1,p_limit) then return false; end if;
  insert into cantoa_public_rate_limits(fingerprint,action)
  values(left(p_fingerprint,128),left(p_action,80));
  return true;
end $$;
revoke all on function public.check_cantoa_public_rate_limit(text,text,integer,integer) from public,anon,authenticated;
grant execute on function public.check_cantoa_public_rate_limit(text,text,integer,integer) to service_role;

insert into public.cantoa_schema_migrations(migration_key)
values('v18.8.49_public_rate_limit_billing_country')
on conflict(migration_key) do nothing;
