-- Cantoa v18.8.29 — Group Song 2.0
-- Safe to run repeatedly.
alter table public.moment_contributions add column if not exists kind text not null default 'memory';
alter table public.moment_contributions add column if not exists feeling text;
alter table public.moment_contributions add column if not exists photo_path text;

create table if not exists public.moment_contribution_votes (
  id bigint generated by default as identity primary key,
  contribution_id bigint not null references public.moment_contributions(id) on delete cascade,
  voter_token text not null,
  created_at timestamptz not null default now(),
  unique(contribution_id,voter_token)
);
create index if not exists moment_contribution_votes_contribution_idx on public.moment_contribution_votes(contribution_id);
alter table public.moment_contribution_votes enable row level security;

insert into public.cantoa_schema_migrations(migration_key)
values('v18.8.29_group_song_2')
on conflict(migration_key) do nothing;
